# DO NOT EDIT THIS FILE!
#
# Python module AAS_CORBA generated by omniidl

import omniORB
omniORB.updateModule("AAS_CORBA")

# ** 1. Stub files contributing to this module
import ICoMapdlUnit_idl

# ** 2. Sub-modules
from . import MAPDL

# ** 3. End
