# DO NOT EDIT THIS FILE!
#
# Python module AAS_CORBA.MAPDL.Solvers generated by omniidl

import omniORB
omniORB.updateModule("AAS_CORBA.MAPDL.Solvers")

# ** 1. Stub files contributing to this module
import ICoMapdlUnit_idl

# ** 2. Sub-modules

# ** 3. End
