# DO NOT EDIT THIS FILE!
#
# Python module AAS_CORBA__POA.MAPDL generated by omniidl

import omniORB
omniORB.updateModule("AAS_CORBA__POA.MAPDL")

# ** 1. Stub files contributing to this module
import ICoMapdlUnit_idl

# ** 2. Sub-modules
from . import Exceptions
from . import Solvers
from . import Types

# ** 3. End
